college_info/urls.py
from django.urls import path
from . import views

app_name="college_info"

urlpatterns = [
    # path("",views.index,name="index"),
    path("sections/<str:section>/<str:college_code>",views.sections,name="sections"),
    path("<str:college>", views.index, name="index"),
]

eamcet_colleges/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#
from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('home/', include("home.urls")),
    path('sort_colleges/', include("sort_colleges.urls")),
    path('college/', include("college_info.urls")),
    url(r'^static/(?P<path>.*)$',serve,{"document_root":settings.STATIC_ROOT}),#this line is very important... this makes the static files work in debug=false after python manage.py collectstatic
    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT}),#this line is very important... this makes the static files work in debug=false after python manage.py collectstatic
]

home/urls.py
from django.urls import path
from . import views


app_name="home"
urlpatterns = [
    path("",views.homepage,name="homepage"),
    path("home", views.index, name="index"),
]

sort_colleges/urls.py
from django.urls import path
from . import views


app_name="sort_colleges"
urlpatterns = [
    path("", views.index, name="index"),
    path("display",views.display, name="display")
]

home/views.py
from django.shortcuts import render
# from django.http import HttpResponse
# from pathlib import Path
# import sys
# Create your views here.

# _pp = str(Path().resolve()).split("\\")
# _ind = len(_pp)-1-(_pp[::-1].index("home"))
# base_path = "\\".join(_pp[:_ind])
# # print(base_path)
# sys.path.append(base_path)
# print("he")
from colleges import *
# print("heyy")
def index(request):
    sorted_colleges=College.sort_colleges("closing_rank")
    return render(request,r"home/index2.html",{"data_list": enumerate(sorted_colleges)})
    # return HttpResponse(KMIT.name)


def homepage(request):
    return render(request,r"home/homepage.html",{})

home/templates/home/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home\homepage.css' %}">
    <link rel="shortcut icon" href="{% static 'home\favicon.ico' %}" type="image/x-icon">
    <!-- <link href="https://www.favicon.cc/favicon/764/984/favicon.png" rel="icon" type="image/x-icon" > -->
    <title>Eamcet Colleges</title>
</head>
<body>


    <div id ="c1" class="container">
        <div class="btn">
           <div class="shop-now"><a href="{% url 'home:index' %}">Colleges</a></div>
           <div class="snowflake-grid to-left">
              <div class="snowflake-item border-bottom border-right">
                 <div class="sub-items border-right border-bottom pull-down">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-bottom border-left">
                 <div
                    class="sub-items border-right border-bottom r-90 pull-down-right"
                    >
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-right">
                 <div class="sub-items border-right border-bottom r-270 pull-right">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-left">
                 <div class="sub-items border-right border-bottom r-180 pull-left">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
           </div>
           <div class="snowflake-grid to-right">
              <div class="snowflake-item border-bottom border-right">
                 <div class="sub-items border-right border-bottom pull-down">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-bottom border-left">
                 <div
                    class="sub-items border-right border-bottom r-90 pull-down-right"
                    >
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-right">
                 <div class="sub-items border-right border-bottom r-270 pull-right">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-left">
                 <div class="sub-items border-right border-bottom r-180 pull-left">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
           </div>
        </div>
     </div>

     <div id="heading" style="text-align: center;">Eamcet Colleges</div>
     <p class="note" style="display: block; text-align: center;">NOTE: Last updated in mid 2022</p>

    <div class="container">
        <div class="btn">
           <div class="shop-now"><a href="{% url 'sort_colleges:index' %}">Sort Colleges</a></div>
           <div class="snowflake-grid to-left">
              <div class="snowflake-item border-bottom border-right">
                 <div class="sub-items border-right border-bottom pull-down">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-bottom border-left">
                 <div
                    class="sub-items border-right border-bottom r-90 pull-down-right"
                    >
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-right">
                 <div class="sub-items border-right border-bottom r-270 pull-right">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-left">
                 <div class="sub-items border-right border-bottom r-180 pull-left">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
           </div>
           <div class="snowflake-grid to-right">
              <div class="snowflake-item border-bottom border-right">
                 <div class="sub-items border-right border-bottom pull-down">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-bottom border-left">
                 <div
                    class="sub-items border-right border-bottom r-90 pull-down-right"
                    >
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-right">
                 <div class="sub-items border-right border-bottom r-270 pull-right">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
              <div class="snowflake-item border-top border-left">
                 <div class="sub-items border-right border-bottom r-180 pull-left">
                    <div class="m-w-15 m-h-15 border-right border-bottom m-3"></div>
                 </div>
              </div>
           </div>
        </div>
     </div>
    <!-- <button>
        <a href="{% url 'home:index' %}">Home</a>
    </button>
    <button>
        <a href="{% url 'sort_colleges:index' %}">Sort Colleges</a>
    </button> -->

    
</body>
</html>

home/templates/home/index2.html
{% extends 'home/layout.html' %}

{% block header %}
    <div class="header__item"><a id="Slno" class="not_sort_keys keep" href="#">Sl.NO</a></div>
    <div class="header__item"><a id="Code" class="not_sort_keys" href="#">Code</a></div>
    <div class="header__item"><a id="College" class="not_sort_keys" href="#">College</a></div>
    <div class="header__item"><a id="ClosingRank" class="sort_keys" href="#">Closing Rank</a></div>
    <div class="header__item"><a id="Intake" class="sort_keys" href="#">Total Intake</a></div>
    <div class="header__item"><a id="HighestSalary" class="sort_keys" href="#">Highest Salary</a></div>
    <div class="header__item"><a id="LowestSalary" class="sort_keys" href="#">Lowest Salary</a></div>
    <div class="header__item"><a id="SalaryMode" class="sort_keys" href="#">Salary Mode</a></div>
    <div class="header__item"><a id="SalaryMean" class="sort_keys" href="#">Salary Mean</a></div>
    <div class="header__item"><a id="SalaryMedian" class="sort_keys" href="#">Salary Median</a></div>
    <div class="header__item"><a id="TotalOffers" class="sort_keys" href="#">Total Offers</a></div>
    <div class="header__item"><a id="CompaniesVisited" class="sort_keys" href="#">Company Visited</a></div>
    <div class="header__item"><a id="PlacementPercent" class="sort_keys" href="#">Placement Percent</a></div>
    <div class="header__item"><a id="DataYear" class="sort_keys" href="#">Data Year</a></div>

{% endblock %}

                
{% block table %}
    {%for data in data_list%}

        <div class="table-row">		
            <div class="table-data" id="tableSlno">{{data.0 |add:1}}</div>
            <div class="table-data" id="tableCode"><a id="Code-b" href="{% url 'college_info:index' college=data.1.code %}" class="college_select" target="_blank">{{data.1.code}}</a></div>
            <div class="table-data" id="tableCollege"><a id="College-b" href="{% url 'college_info:index' college=data.1.code %}" class="college_select" target="_blank">{{data.1.name}}</a></div>
            <div class="table-data" id="tableClosingRank">{{data.1.closing_rank}}</div>
            <div class="table-data" id="tableIntake">{{data.1.total_intake}}</div>
            <div class="table-data" id="tableHighestSalary">{{data.1.highest_salary}}</div>
            <div class="table-data" id="tableLowestSalary">{{data.1.lowest_salary}}</div>
            <div class="table-data" id="tableSalaryMode">{{data.1.salary_mode}}</div>
            <div class="table-data" id="tableSalaryMean">{{data.1.salary_mean}}</div>
            <div class="table-data" id="tableSalaryMedian">{{data.1.salary_median}}</div>
            <div class="table-data" id="tableTotalOffers">{{data.1.total_offers}}</div>
            <div class="table-data" id="tableCompaniesVisited">{{data.1.companies_visited}}</div>
            <div class="table-data" id="tablePlacementPercent">{{data.1.placement_percent}}</div>
            <div class="table-data" id="tableDataYear">{{data.1.placement_data_year}}</div>
        </div>

    {%endfor%}
{% endblock %}

home/templates/home/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <link rel="stylesheet" href="{% static 'home\layout.css' %}">
    <link rel="shortcut icon" href="{% static 'home\favicon.ico' %}" type="image/x-icon">
    <!-- <link href="https://www.favicon.cc/favicon/764/984/favicon.png" rel="icon" type="image/x-icon" > -->
    <script type="text/javascript" src="{% static 'home\layout.js' %}"></script>
    <title>Document</title>
    {% block link %}
    {% endblock %}

</head>
<body>
    <h2 class="heading">Eamcet Colleges</h3>
        <span>Click on a college to view more information.&nbsp;&nbsp;</span>
        <span>Click on a heading to sort accordingly.</span>
        <a href="{% url 'home:homepage' %}"  style="font-family:cursive; font-size:large; padding-left:20px; color:black;">Home</a>
    <div class="container">
	
        <div class="table">
            <div class="table-header">
                {% block header %}
                {% endblock %}
            
            </div>
            <div class="table-content"> 
                {% block table %}
                {% endblock %}
            
            </div>	
        </div>
    </div>
</body>
</html>