college_info/urls.py
from django.urls import path
from . import views

app_name="college_info"

urlpatterns = [
    # path("",views.index,name="index"),
    path("sections/<str:section>/<str:college_code>",views.sections,name="sections"),
    path("<str:college>", views.index, name="index"),
]

eamcet_colleges/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#
from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('home/', include("home.urls")),
    path('sort_colleges/', include("sort_colleges.urls")),
    path('college/', include("college_info.urls")),
    url(r'^static/(?P<path>.*)$',serve,{"document_root":settings.STATIC_ROOT}),#this line is very important... this makes the static files work in debug=false after python manage.py collectstatic
    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT}),#this line is very important... this makes the static files work in debug=false after python manage.py collectstatic
]

home/urls.py
from django.urls import path
from . import views


app_name="home"
urlpatterns = [
    path("",views.homepage,name="homepage"),
    path("home", views.index, name="index"),
]

sort_colleges/urls.py
from django.urls import path
from . import views


app_name="sort_colleges"
urlpatterns = [
    path("", views.index, name="index"),
    path("display",views.display, name="display")
]

sort_colleges/forms.py
from logging import PlaceHolder
from django import forms

class FormStudent(forms.Form):
    form_rank= forms.IntegerField(required=True,max_value=100000,min_value=1,label="Eamcet Rank")
    form_gender=forms.CharField(required=True,label="Gender",widget=forms.RadioSelect(choices=[("Boys","Male"), ("Girls","Female")]))
    
    form_category=forms.CharField(required=True,label="Category",widget=forms.RadioSelect(choices=[("OC","OC"),("BC_A","BC_A"),("BC_B","BC_B"),("BC_C","BC_C"),("BC_D","BC_D"),("BC_E","BC_E"),("SC","SC"),("ST","ST")]))
    form_branch_categories=forms.CharField(required=True,label="Branch Categories",widget=forms.CheckboxSelectMultiple(choices=[('COMPUTER','COMPUTER'), ('COMPUTER_2','COMPUTER_2'), ('ELECTRICAL','ELECTRICAL'), ('COMPUTER_3','COMPUTER_3'),
             ('ELECTRICAL_2','ELECTRICAL_2'), ('MECHANICAL','MECHANICAL'), ('MECHANICAL_2','MECHANICAL_2'), ('CHEMICAL','CHEMICAL'), ('PHARMACY','PHARMACY')]))
    
    form_latitude=forms.FloatField(required=True, label="Latitude",min_value=15,max_value=20)
    form_longitude=forms.FloatField(required=True, label="Longitude",min_value=77 ,max_value=82)

    form_sorting_key=forms.CharField(required=True,label="Sorting Key",widget=forms.RadioSelect(choices=[('placement_percent','placement_percent'), ('highest_salary','highest_salary'), 
    ('lowest_salary','lowest_salary'), ('salary_mode','salary_mode'), ('salary_mean','salary_mean'), ('salary_median','salary_median'), ('total_offers','total_offers'), ('companies_visited','companies_visited'), ('year','year'), 
            ('total_intake','total_intake'), ('fees','fees'), ('probability','probability'), ('closing_rank','closing_rank'), ('distance','distance')]))

#     form_visible_fields=forms.CharField(required=True ,label="Visible fields",widget=forms.CheckboxSelectMultiple(choices=[("name","College name"),("closing_rank","Closing rank"),
#     ("total_intake","Total intake"),("highest_salary","Highest offer"),("lowest_salary","Lowest offer"),("salary_mean","Offer mean"),
#     ("salary_median","Offer median"),("salary_mode","Offer mode"),("total_offers","Total offers"),("companies_visited","Companies visited"),
#     ("placement_percent","Placement percentage"),("placement_data_year","Placement data year"),
    
#     ("district","District"),("phone","Phone number"),("address","Address"),]))
    

sort_colleges/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from pathlib import Path
import sys
from .forms import FormStudent
from json import loads
# Create your views here.

# _pp = str(Path().resolve()).split("\\")
# _ind = len(_pp)-1-(_pp[::-1].index("sort_colleges"))
# base_path = "\\".join(_pp[:_ind])
# # print(base_path)
# sys.path.append(base_path)

from colleges import *


def index(request):
        if request.method == "POST":

            try:
                filled_form = FormStudent(request.POST)

                if filled_form.is_valid():
                    form_data = filled_form.cleaned_data
                    print(form_data)
                    return display(form_data,request)

                else: return render(request,r"sort_colleges/index3.html",{"form":FormStudent(filled_form)})


            except AttributeError as er:
                er=str(er) 
                if "FormStudent"in er and "get" in er:
                    return render(request,r"sort_colleges/index3.html",{"warning":"please select at least one category","form":FormStudent()})
                else:return HttpResponse("Errrrrr")
        else:
            return render(request,r"sort_colleges/index3.html",{"form":FormStudent()})
            

def display(data,request):
    College.calculate_dist((data["form_latitude"],data["form_longitude"]))
    College.chance_college(data["form_rank"],data["form_gender"],data["form_category"],loads(data["form_branch_categories"].replace("'",'"')))
    colleges=College.sort_colleges(data["form_sorting_key"])
    # return HttpResponse(data["form_branch_categories"].replace("'",'"'))
    detailed_colleges=[]
    for i,college in enumerate(colleges):
        detailed_colleges.append((i,college,getattr(college,data["form_sorting_key"])))
        

    return render(request,r"sort_colleges/display.html",{"key":data["form_sorting_key"],"data_list":detailed_colleges})

sort_colleges/templates/sort_colleges/display.html
{% extends 'home/layout.html' %}
{% load static %}


{% block link %}
<script src="{% static 'sort_colleges\display.js' %}"></script>
{% endblock %}


{% block header %}
    <div class="header__item"><a id="Slno" class="not_sort_keys" href="#">Sl.NO</a></div>
    <div class="header__item"><a id="Code" class="not_sort_keys" href="#">Code</a></div>
    <div class="header__item"><a id="College" class="not_sort_keys" href="#">College</a></div>
    <div class="header__item"><a id="ClosingRank" class="sort_keys" href="#">Closing Rank</a></div>
    {% if key != 'closing_rank' and key != 'distance' and key != 'probability' %}
        <div class="header__item"><a id="OriginalSort" class="not_sort_keys" href="#">{{key}}</a></div>
    {% endif %}
    <div class="header__item"><a id="Distance" class="sort_keys" href="#">Distance (km)</a></div>
    <div class="header__item"><a id="Probability" class="sort_keys" href="#">Probability</a></div>

{% endblock %}


{% block table %}

    {%for data in data_list%}
        <div class="table-row">		
            <div class="table-data" id="tableSlno">{{data.0 |add:1}}</div>
            <div class="table-data" id="tableCode"><a id="Code-b" href="{% url 'college_info:index' college=data.1.code %}" class="college_select" target="_blank">{{data.1.code}}</a></div>
            <div class="table-data" id="tableCollege"><a id="College-b" href="{% url 'college_info:index' college=data.1.code %}" class="college_select" target="_blank">{{data.1.name}}</a></div>
            <div class="table-data" id="tableClosingRank">{{data.1.closing_rank}}</div>
            {% if key != 'closing_rank' and key != 'distance' and key != 'probability' %}
                <div class="table-data" id="tableOriginalSort">{{data.2}}</div>
            {% endif %}
            <div class="table-data" id="tableDistance">{{data.1.distance | floatformat:2}}</div>
            <div class="table-data" id="tableProbability">{{data.1.probability | floatformat:2}}</div>
        </div>
    {%endfor%}

{% endblock %}

sort_colleges/templates/sort_colleges/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'sort_colleges\favicon.ico' %}" type="image/x-icon">
    <!-- <link href="https://www.favicon.cc/favicon/764/984/favicon.png" rel="icon" type="image/x-icon" > -->
    <title>Eamcet Colleges</title>
</head>
<body>
    <form action="{% url 'sort_colleges:index' %}" method="post">
        {% csrf_token %}

        {{form}}

        <input type="submit",target="_blank">
    </form>
    
</body>
</html>

sort_colleges/templates/sort_colleges/index2.html
<!DOCTYPE html>
<html>
<head>
<style>
    .button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}
</style>   
<title>Eamcet Colleges</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="shortcut icon" href="{% static 'sort_colleges\favicon.ico' %}" type="image/x-icon">
<!-- <link href="https://www.favicon.cc/favicon/764/984/favicon.png" rel="icon" type="image/x-icon" > -->

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
    <a href="#home" class="w3-bar-item w3-button"><b>EAMCET</b> DUNIA</a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="#projects" class="w3-bar-item w3-button">Projects</a>
      <a href="#about" class="w3-bar-item w3-button">About</a>
      <a href="#contact" class="w3-bar-item w3-button">Contact</a>
    </div>
  </div>
</div>

<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
  <img src="C:/image/dow.jpg" alt="image" width="" height="800">
  <div class="w3-display-middle w3-margin-top w3-center">
    <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>AMS</b></span> <span class="w3-hide-small w3-text-light-green">TECH</span></h1>
  </div>
</header>

<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">

  <!-- Project Section -->
  <div class="w3-container w3-padding-32" id="projects">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">EAMCET STUDENT PORTAL</h3>
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eamcet Colleges</title>
</head>
<body>
    <form action="/sort_colleges/" method="post">
        <input type="hidden" name="csrfmiddlewaretoken" value="VtLKjX25X7eqUZ5lHcuaOe5Nz2ftbtU1XpC85p1QLrrxohuw4Tmq8hNIsYzWqLzP">

        <tr>
    <th><label for="id_form_rank">Eamcet Rank:</label></th>
    <td>
      
      <input type="number" name="form_rank" min="1" max="100000" required id="id_form_rank">
      
      
    </td>
  </tr>

  <tr>
    <th><label>
        <p>Gender:</label></th><p>
    <td>
      
      <div id="id_form_gender"><div>
    <label for="id_form_gender_0"><input type="radio" name="form_gender" value="Boys" required id="id_form_gender_0">
 Male</label>

</div><div>
    <label for="id_form_gender_1"><input type="radio" name="form_gender" value="Girls" required id="id_form_gender_1">
 Female</label>

</div>
</div>
      
      
    </td>
  </tr>

  <tr>
    <th><label>Category:</label></th>
    <td>
      
      <div id="id_form_category"><div>
    <label for="id_form_category_0"><input type="radio" name="form_category" value="OC" required id="id_form_category_0">
 OC</label>

</div><div>
    <label for="id_form_category_1"><input type="radio" name="form_category" value="BC_A" required id="id_form_category_1">
 BC_A</label>

</div><div>
    <label for="id_form_category_2"><input type="radio" name="form_category" value="BC_B" required id="id_form_category_2">
 BC_B</label>

</div><div>
    <label for="id_form_category_3"><input type="radio" name="form_category" value="BC_C" required id="id_form_category_3">
 BC_C</label>

</div><div>
    <label for="id_form_category_4"><input type="radio" name="form_category" value="BC_D" required id="id_form_category_4">
 BC_D</label>

</div><div>
    <label for="id_form_category_5"><input type="radio" name="form_category" value="BC_E" required id="id_form_category_5">
 BC_E</label>

</div><div>
    <label for="id_form_category_6"><input type="radio" name="form_category" value="SC" required id="id_form_category_6">
 SC</label>

</div><div>
    <label for="id_form_category_7"><input type="radio" name="form_category" value="ST" required id="id_form_category_7">
 ST</label>

</div>
</div>
      
      
    </td>
  </tr>

  <tr>
    <th><label>Branch Categories:</label></th>
    <td>
      
      <div id="id_form_branch_categories"><div>
    <label for="id_form_branch_categories_0"><input type="checkbox" name="form_branch_categories" value="COMPUTER" id="id_form_branch_categories_0">
 COMPUTER</label>

</div><div>
    <label for="id_form_branch_categories_1"><input type="checkbox" name="form_branch_categories" value="COMPUTER_2" id="id_form_branch_categories_1">
 COMPUTER_2</label>

</div><div>
    <label for="id_form_branch_categories_2"><input type="checkbox" name="form_branch_categories" value="ELECTRICAL" id="id_form_branch_categories_2">
 ELECTRICAL</label>

</div><div>
    <label for="id_form_branch_categories_3"><input type="checkbox" name="form_branch_categories" value="COMPUTER_3" id="id_form_branch_categories_3">
 COMPUTER_3</label>

</div><div>
    <label for="id_form_branch_categories_4"><input type="checkbox" name="form_branch_categories" value="ELECTRICAL_2" id="id_form_branch_categories_4">
 ELECTRICAL_2</label>

</div><div>
    <label for="id_form_branch_categories_5"><input type="checkbox" name="form_branch_categories" value="MECHANICAL" id="id_form_branch_categories_5">
 MECHANICAL</label>

</div><div>
    <label for="id_form_branch_categories_6"><input type="checkbox" name="form_branch_categories" value="MECHANICAL_2" id="id_form_branch_categories_6">
 MECHANICAL_2</label>

</div><div>
    <label for="id_form_branch_categories_7"><input type="checkbox" name="form_branch_categories" value="CHEMICAL" id="id_form_branch_categories_7">
 CHEMICAL</label>

</div><div>
    <label for="id_form_branch_categories_8"><input type="checkbox" name="form_branch_categories" value="PHARMACY" id="id_form_branch_categories_8">
 PHARMACY</label>

</div>
</div>
      
      
    </td>
  </tr>

  <tr>
      <P>PLEASE ENTER UR LOCATION EX:[17.56(LATITUDE),17.77(LONGITUDE)]<P>
    <th><label for="id_form_latitude">Latitude:</label></th>
    <td>
      
      <input type="number" name="form_latitude" min="15" max="20" step="any" required id="id_form_latitude">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_form_longitude">Longitude:</label></th>
    <td>
      
      <input type="number" name="form_longitude" min="77" max="82" step="any" required id="id_form_longitude">
      
      
    </td>
  </tr>

  <tr>
    <p><th><label>Sorting Key:</label></th></p>
    <td>
      
      <div id="id_form_sorting_key"><div>
    <label for="id_form_sorting_key_0"><input type="radio" name="form_sorting_key" value="placement_percent" required id="id_form_sorting_key_0">
 placement_percent</label>

</div><div>
    <label for="id_form_sorting_key_1"><input type="radio" name="form_sorting_key" value="highest_salary" required id="id_form_sorting_key_1">
 highest_salary</label>

</div><div>
    <label for="id_form_sorting_key_2"><input type="radio" name="form_sorting_key" value="lowest_salary" required id="id_form_sorting_key_2">
 lowest_salary</label>

</div><div>
    <label for="id_form_sorting_key_3"><input type="radio" name="form_sorting_key" value="salary_mode" required id="id_form_sorting_key_3">
 salary_mode</label>

</div><div>
    <label for="id_form_sorting_key_4"><input type="radio" name="form_sorting_key" value="salary_mean" required id="id_form_sorting_key_4">
 salary_mean</label>

</div><div>
    <label for="id_form_sorting_key_5"><input type="radio" name="form_sorting_key" value="salary_median" required id="id_form_sorting_key_5">
 salary_median</label>

</div><div>
    <label for="id_form_sorting_key_6"><input type="radio" name="form_sorting_key" value="total_offers" required id="id_form_sorting_key_6">
 total_offers</label>

</div><div>
    <label for="id_form_sorting_key_7"><input type="radio" name="form_sorting_key" value="companies_visited" required id="id_form_sorting_key_7">
 companies_visited</label>

</div><div>
    <label for="id_form_sorting_key_8"><input type="radio" name="form_sorting_key" value="year" required id="id_form_sorting_key_8">
 year</label>

</div><div>
    <label for="id_form_sorting_key_9"><input type="radio" name="form_sorting_key" value="total_intake" required id="id_form_sorting_key_9">
 total_intake</label>

</div><div>
    <label for="id_form_sorting_key_10"><input type="radio" name="form_sorting_key" value="fees" required id="id_form_sorting_key_10">
 fees</label>

</div><div>
    <label for="id_form_sorting_key_11"><input type="radio" name="form_sorting_key" value="probability" required id="id_form_sorting_key_11">
 probability</label>

</div><div>
    <label for="id_form_sorting_key_12"><input type="radio" name="form_sorting_key" value="closing_rank" required id="id_form_sorting_key_12">
 closing_rank</label>

</div><div>
    <label for="id_form_sorting_key_13"><input type="radio" name="form_sorting_key" value="distance" required id="id_form_sorting_key_13">
 distance</label>

</div>
</div>
      
      
        
      
    </td>
  </tr>

        <p><input type="SUBMIT" class="button" value="SUBMIT"></p>
    </form>
  <!-- About Section -->
  <div class="w3-container w3-padding-32" id="about">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">About</h3>
    <p> We know the difficulty in finding the colleges that suit us accordingly to our EAMCET rank, many different sites show us different types of results. Student gets confused what to believe and what to not. When it comes to placements, there is no tool that gives data of all colleges, or compares the colleges based on the same.
So, we have come up with a project idea that helps a student to find which college is better and gives the student an idea of which college to choose according to the placements and different factors that decide the credibility of an engineering college.

    </p>
  </div>

  <div class="w3-row-padding w3-grayscale">
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="C:/image/dow.jpg" alt="image" style="width:100%">
      <h3>ARSHAD ALI</h3>
      <p class="w3-opacity">CEO & Founder</p>
      <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
      <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="/w3images/team1.jpg" alt="Jane" style="width:100%">
      <h3>MONISH</h3>
      <p class="w3-opacity">Architect</p>
      <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
      <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="/w3images/team3.jpg" alt="Mike" style="width:100%">
      <h3>SRIKAR</h3>
      <p class="w3-opacity">Architect</p>
      <p>Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.</p>
      <p><button class="w3-button w3-light-grey w3-block">Contact</button></p>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      
    </div>
  </div>

  <!-- Contact Section -->
  <div class="w3-container w3-padding-32" id="contact">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Contact</h3>
    <p>Lets get in touch and talk about your next project.</p>
    <form action="/action_page.php" target="_blank">
      <input class="w3-input w3-border" type="text" placeholder="Name" required name="Name">
      <input class="w3-input w3-section w3-border" type="text" placeholder="Email" required name="Email">
      <input class="w3-input w3-section w3-border" type="text" placeholder="Subject" required name="Subject">
      <input class="w3-input w3-section w3-border" type="text" placeholder="Comment" required name="Comment">
      <button class="w3-button w3-black w3-section" type="submit">
        <i class="fa fa-paper-plane"></i> SEND MESSAGE
      </button>
    </form>
  </div>
  
<!-- Image of location/map -->
<div class="w3-container">
  <img src="/w3images/map.jpg" class="w3-image" style="width:100%">
</div>

<!-- End page content -->
</div>


<!-- Footer -->
<footer class="w3-center w3-black w3-padding-16">
  <a style="text-decoration:none;" href="{% url 'home:homepage' %}" title="kmit.in" target="_blank" class="w3-hover-text-green"><p>Home</p></a>
</footer>
<p style="text-align:center">Template by w3schools.</p>

</body>
</html>