college_info/urls.py
from django.urls import path
from . import views

app_name="college_info"

urlpatterns = [
    # path("",views.index,name="index"),
    path("sections/<str:section>/<str:college_code>",views.sections,name="sections"),
    path("<str:college>", views.index, name="index"),
]

eamcet_colleges/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#
from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('home/', include("home.urls")),
    path('sort_colleges/', include("sort_colleges.urls")),
    path('college/', include("college_info.urls")),
    url(r'^static/(?P<path>.*)$',serve,{"document_root":settings.STATIC_ROOT}),#this line is very important... this makes the static files work in debug=false after python manage.py collectstatic
    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT}),#this line is very important... this makes the static files work in debug=false after python manage.py collectstatic
]

home/urls.py
from django.urls import path
from . import views


app_name="home"
urlpatterns = [
    path("",views.homepage,name="homepage"),
    path("home", views.index, name="index"),
]

college_info/models.py
from django.db import models

# Create your models here.

college_info/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from pandas import read_excel
# Create your views here.

from colleges import *

#TODO check whether we can import using exec, to just import the college needed.
#TODO fix the back button... and add that clicking college name takes to this page in a new tab.
def index(request,college:str):
    college=college.upper()
    college=College.instances.get(college,None)
    if not college: return HttpResponse("""Error 404 ....................wrong college..""")

    return render(request,'college_info/index.html',{"college":college})


def sections(request,section:str,college_code:str):

    college=college_code.upper()
    college=College.instances.get(college,None)
    if not college: return HttpResponse("""Error 404 ....................wrong college for section..""")

    
    #placement analysis and details.
    placement_analysis_available=all((college.highest_salary,college.salary_mean,college.companies_visited,college.total_offers))
    placement_details_available=any((college.highest_salary,college.salary_mean,college.companies_visited,college.total_offers))

    if placement_details_available:

        file_placement_detail=f"Files/college_info/all_colleges/{college.code}/{college.code}_placements.xlsx"

        df=read_excel(file_placement_detail,index_col=0)
        placement_data=enumerate((df.to_dict('split'))["data"],1)
    else:
        placement_data=None





    #sections.
    match(section):
        case "demo":
            return render(request,'college_info/demo.html')
        case "eamcet":
            return render(request,'college_info/section_eamcet.html',{"college":college})
        case "placement":
            return render(request,'college_info/section_placement.html',{"college":college, "placement_analysis_available":placement_analysis_available, "placement_details_available":placement_details_available,"placement_data":placement_data})
        case "clsrnk":
            return render(request,'college_info/section_clsrnk.html',{"college":college})
        
        case _ :
            raise Http404 #404 page not found web error..
            
    

college_info/templates/college_info/demo.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'college_info/demo.js' %}"></script>
    <title>Document</title>
    <style>
        /* hides scrollbar, but still able to scroll */
        .container::-webkit-scrollbar { 
            display: none;  /* Safari and Chrome */
        }
    </style>
</head>
<body style="background-color:rgb(240, 232, 215)" class="container" >
    <iframe id="sections" src="{% url 'college_info:index' college='CBIT' %}" width="100%" text-align="center" height="0" marginheight="0" marginwidth="0" frameborder="0" style="width: 100%; display:block;">
        <!-- height to be set by javascript equal to device window height... -->
    </iframe>

    
</body>
</html>

college_info/templates/college_info/index.html
{%load static%}
<!DOCTYPE html lang="en">
<html>
<head><title>
	{{college.name}}
</title>
    
    <meta charset="utf-8" />
    <!-- <meta content="width=device-width, initial-scale=1.0" name="viewport" /> -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> -->
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no" /> -->
    <meta name="referrer" content="origin" /> 
    <!-- Favicons -->


    <!--  CSS Files -->
    <!-- <link href="required/aos/aos.css" rel="stylesheet" />
    <link href="required/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="required/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
    <link href="required/boxicons/css/boxicons.min.css" rel="stylesheet" />
    <link href="required/glightbox/css/glightbox.min.css" rel="stylesheet" />
    <link href="required/swiper/swiper-bundle.min.css" rel="stylesheet" /> -->

    <!-- Template Main CSS File -->
    <!-- <link href="{%static 'college_info/index.css' %}" rel="stylesheet" /> -->
    <!-- <link href="{%static 'college_info/index_2.css' %}" rel="stylesheet" type="text/css" /> -->
    <link rel="shortcut icon" href="{% static 'college_info/favicon.ico' %}" type="image/x-icon">
    <meta http-equiv="Cache-control" content="no-cache" /> <!-- page details may not be cached by Bowser / Search engine memory-->
    <meta http-equiv="Cache-control" content="no-store" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Cache-control" content="must-revalidate" />
    <script src="{% static 'college_info/index.js' %}"></script>

    
    
    
    <!-- <script type="text/javascript" src="Scripts/validations.js"></script>
    <script src="Scripts/jquery-3.5.1.js"  type="text/javascript"></script>
    <script src="Scripts/jquery-3.5.1.min.js" type="text/javascript"></script> -->


    <style type='text/css' media='print'>
            img.NoPrint {display:none;}
            p.NonPrintable {display:none;}
            .nonl {clear:none;}
            .NP {display:none;}
    </style>

    <script type="text/javascript" language="javascript">
        $(document).ready(function () {

            $(document).bind("contextmenu", function (e) {
                return false;
            });
            window.history.pushState(null, "", window.location.href);
            window.addEventListener('popstate', function () {
                window.history.pushState(null, "", window.location.href);

            });
        });
    </script>

    <!-- <script type="text/javascript" language="javascript">
           var ua = window.navigator.userAgent;
           //alert( "gan :  " + ua);
           var msie = ua.indexOf("MSIE ");
           if (msie > 0) {
               //alert ("Duplicate values not found................" + msie);
               javascript: window.history.forward(1);
           }
    
     </script> -->

    
   
<!-- <link href="/Styles/SiteTSEAMCET.css" type="text/css" rel="stylesheet" /> -->
<style>
    table{
        border-collapse:collapse;
        border-color: black;
    }
    body{
        background-color: rgb(240, 232, 215);
    }
    .heading{
        text-align: center;
        margin-bottom: 30px;
        margin-top: 30px;
	    font-family: 'Dancing Script', cursive;
    }
    body::-webkit-scrollbar { 
            display: none;  /* Safari and Chrome */
    }
</style>
</head>


<body>
   
    <h2 class="heading" id="heading">{{ college.name }} -({{ college.code }})</h2>
    <p hidden id="college_code">{{ college.code }}</p>
    

    <!-- ======= Top Bar ======= -->
    <!-- <section id="topbar" class="d-flex align-items-center" style="background-color:#03385A;">
        <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center bold ">
                TELANGANA STATE COUNCIL OF HIGHER EDUCATION
            </div>
            <div  id="helpline" class="social-links d-none d-md-flex align-items-center">
                Help Desk Phone Numbers : 7660009768, 7660009769
            </div>
        </div>
    </section> -->

        <!-- ======= Header ======= -->
        <header id="header" class="d-flex align-items-center">
        <div class="container d-flex  ">
            <!-- <img alt="Home page" src="{% static 'college_info/favicon.ico' %}" height="40" width="40" style="margin-top:0px; margin-right:10px; margin-top:4px;" /> -->
            <!-- <a href="{% url 'home:homepage' %}"  style="font-family:cursive; font-size:large; padding-top:0px; color:black;">Home</a> -->

            <!-- <nav id="navbar" class="navbar">
            <ul>
              <li><a class="nav-link scrollto " href="Default.aspx"><i class="bi bi-house-door-fill"></i></a></li>

             
                         <li><a class="nav-link scrollto " href="/cand_login.aspx">Candidates Login</a></li>  
              

          
               <li><a class="nav-link scrollto" href="ContactUs_dum.aspx">Contact Us</a></li> 
              <li><a class="nav-link scrollto" href="Logout.aspx">Logout</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
          </nav> -->
          <!-- .navbar -->

        </div>
    </header>
        <!-- End Header -->

     <!-- <form method="post" action="./institute_details.aspx?iCode=ACEG" id="ctl01" autocomplete="OFF"> -->
    <div class="nav-bar">
        <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
        <style>
            .nav-bar{
                display:table;
                width:100%;
                align-items:center;
                text-align: center;
                margin-bottom: 2vh;
            }
            .nav-elements{
                display:inline;
                position:relative;
                margin: 0;
            }
            a {
              display: inline;
              color: rgb(0, 0, 0);
              text-align: center;
              padding: 3vw;
              text-decoration: none;
              font-size: larger;
            }

            /* Change the link color to #111 (black) on hover */

        </style>
            <div class="nav-elements"><a class="nav-a"  href="#" data-link="eamcet">Eamcet</a></div>
            <div class="nav-elements"><a class="nav-a"  href="#" data-link="placement">Placement</a></div>
            <div class="nav-elements"><a class="nav-a"  href="#" data-link="clsrnk">Closing ranks</a></div>
    </div>
    
<iframe id="sections" src="{% url 'college_info:sections' section='eamcet' college_code=college.code %}" width="100%" text-align="center" height="10" marginheight="0" marginwidth="0" frameborder="0" style="width: 100%; display:block;">
    <!-- height to be set by javascript equal to device window height... -->
</iframe>

college_info/templates/college_info/section_clsrnk.html
{%load dict_get%}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="{% static 'college_info/favicon.ico' %}" type="image/x-icon">

    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <title>{{college.name}}</title>
</head>
<body>
    <div class="nav-bar">
        <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
        <style>
            .nav-bar{
                display:table;
                width:100%;
                align-items:center;
                text-align: center;
                margin-bottom: 6vh;
            }
            .nav-elements{
                display:inline;
                position:relative;
                margin: 0;
            }
            .nav-a {
              display: inline;
              color: rgb(0, 0, 0);
              text-align: center;
              padding: 10vw;
              text-decoration: none;
              font-size: larger;
            }

            /* Change the link color to #111 (black) on hover */

        </style>
            <div class="nav-elements"><a class="nav-a"  href="#" data-link="table_2021"><b>2021</b></a></div>
            <div class="nav-elements"><a class="nav-a"  href="#" data-link="table_2020"><b>2020</b></a></div>
            <div class="nav-elements"><a class="nav-a"  href="#" data-link="table_2019"><b>2019</b></a></div>
    </div>




<script>
    document.addEventListener("DOMContentLoaded",()=>{
        console.log("hellooo");
        document.querySelectorAll(".nav-a").forEach((element) => {
        element.addEventListener("click",(event) => {

            console.log(element.dataset.link)
            // hiding all
            document.querySelectorAll(".container, .heading").forEach((element3) => {
                element3.style.display="none";
            })

            // making one visible
            document.querySelectorAll(`.${element.dataset.link}`).forEach((element2)=>{
                element2.style.display="flex";
            })
        })
    })
    })
</script>
<!-- for table -->
    <link rel="stylesheet" href="{% static 'home\layout.css' %}">
    <script type="text/javascript" src="{% static 'home\layout.js' %}"></script>
    
<!-- 2021 -->
        <h2 class="table_2021 heading" style="margin-bottom:0.5vh; display:flex;"><b>Year: 2021</b><br><br></h2>
        <div class="container table_2021" style="display:flex;">
	
            <div class="table">
                <div class="table-header">
                    <div class="header__item"><a class="not_sort_keys keep" href="#">Branch</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">Gender</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">OC</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_A</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_B</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_C</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_D</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_E</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">SC</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">ST</a></div>
                
                </div>
                <div class="table-content">
                    {% for branch in college.branches %} 
                        <div class="table-row"  >
                            <div class="table-data" >{{branch.name}}</div>
                            <div class="table-data" >Boys</div>
                            <div class="table-data" >{{ branch.clsrnk21|get_space:"OC BOYS" }}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_A BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_B BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_C BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_D BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_E BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"SC BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"ST BOYS"}}</div>
                        </div>
                        <div class="table-row" >
                            <div class="table-data" >{{branch.code}}</div>
                            <div class="table-data" >Girls</div>
                            <div class="table-data" >{{ branch.clsrnk21|get_space:"OC GIRLS" }}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_A GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_B GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_C GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_D GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"BC_E GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"SC GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk21|get_space:"ST GIRLS"}}</div>
                        </div>
                        <div class="table-row" style="background-color:rgba(0, 0, 0, 0.3); border:none;"></div>
                    {% endfor %}
                </div>	
            </div>
        </div>


<!-- 2020 -->
        <h2 class="table_2020 heading" style="margin-bottom:0.5vh; display:none;"><b>Year: 2020</b><br><br></h2>
        <div class="container table_2020" style="display:none;">
	
            <div class="table">
                <div class="table-header">
                    <div class="header__item"><a class="not_sort_keys keep" href="#">Branch</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">Gender</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">OC</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_A</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_B</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_C</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_D</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_E</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">SC</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">ST</a></div>
                
                </div>
                <div class="table-content">
                    {% for branch in college.branches %} 
                        <div class="table-row"  >
                            <div class="table-data" >{{branch.name}}</div>
                            <div class="table-data" >Boys</div>
                            <div class="table-data" >{{ branch.clsrnk20|get_space:"OC BOYS" }}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_A BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_B BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_C BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_D BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_E BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"SC BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"ST BOYS"}}</div>
                        </div>
                        <div class="table-row" >
                            <div class="table-data" >{{branch.code}}</div>
                            <div class="table-data" >Girls</div>
                            <div class="table-data" >{{ branch.clsrnk20|get_space:"OC GIRLS" }}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_A GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_B GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_C GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_D GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"BC_E GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"SC GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk20|get_space:"ST GIRLS"}}</div>
                        </div>
                        <div class="table-row" style="background-color:rgba(0, 0, 0, 0.3); border:none;"></div>
                    {% endfor %}
                </div>	
            </div>
        </div>


<!-- 2019 -->
        <h2 class="table_2019 heading" style="margin-bottom:0.5vh; display:none;"><b>Year: 2019</b><br><br></h2>
        <div class="container table_2019" style="display:none;">
	
            <div class="table">
                <div class="table-header">
                    <div class="header__item"><a class="not_sort_keys keep" href="#">Branch</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">Gender</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">OC</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_A</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_B</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_C</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_D</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">BC_E</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">SC</a></div>
                    <div class="header__item"><a class="not_sort_keys" href="#">ST</a></div>
                
                </div>
                <div class="table-content">
                    {% for branch in college.branches %} 
                        <div class="table-row"  >
                            <div class="table-data" >{{branch.name}}</div>
                            <div class="table-data" >Boys</div>
                            <div class="table-data" >{{ branch.clsrnk19|get_space:"OC BOYS" }}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_A BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_B BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_C BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_D BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_E BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"SC BOYS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"ST BOYS"}}</div>
                        </div>
                        <div class="table-row" >
                            <div class="table-data" >{{branch.code}}</div>
                            <div class="table-data" >Girls</div>
                            <div class="table-data" >{{ branch.clsrnk19|get_space:"OC GIRLS" }}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_A GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_B GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_C GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_D GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"BC_E GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"SC GIRLS"}}</div>
                            <div class="table-data" >{{branch.clsrnk19|get_space:"ST GIRLS"}}</div>
                        </div>
                        <div class="table-row" style="background-color:rgba(0, 0, 0, 0.3); border:none;"></div>
                    {% endfor %}
                </div>	
            </div>
        </div>
    
</body>
</html>

college_info/templates/college_info/section_placement.html
{%load static%}
<!DOCTYPE html lang="en">
<html>
<head><title>
	{{college.name}}
</title>
    
    <meta charset="utf-8" /><meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> -->
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no" />
    <meta name="referrer" content="origin" /> 


    <link rel="shortcut icon" href="{% static 'college_info/favicon.ico' %}" type="image/x-icon">
    <meta http-equiv="Cache-control" content="no-cache" /> <!-- page details may not be cached by Bowser / Search engine memory-->
    <meta http-equiv="Cache-control" content="no-store" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Cache-control" content="must-revalidate" />



<style>
    table{
        border-collapse:collapse;
        border-color: black;
    }
    body{
        background-color: rgb(240, 232, 215);
    }
    .heading{
        text-align: center;
        margin-bottom: 30px;
        margin-top: 30px;
	    font-family: 'Dancing Script', cursive;
    }
</style>
</head>


<body>

    <h3 class="heading" id="heading">Placement analysis</h2>
<div class="main">
            
<style>
  th, td {
    border-collapse: collapse;
    border: 1px solid;
    font-family:Verdana, Geneva, Tahoma, sans-serif;
    padding-bottom: 2px;
    padding-top: 2px;
}

</style>
 
            <br />
            <table class="textd" style="border-style:solid; border-width:thin; " align="center" bgcolor="#BFB5B7" border="2" bordercolor="#ffffff" width="95%">
                   <!-- <tr> -->
                    <!-- <td>{{ college.name }} -({{ college.code }})</td> -->
                    <!-- <td align="right" colspan="4" >
                        <a href='institute_profile.aspx'><img src='images/back.jpg' alt="Back" width="20" height="24"></a>
                   </td> -->
                   <!-- </tr>  -->
                   <tr valign="top">
                    <td align="left" bgcolor="#F9F3D7">Highest Salary :</td>
                    <td align="left" bgcolor="#ffffff">&nbsp;{{college.highest_salary}}</td>
                    <td align="left" bgcolor="#F9F3D7">Lowest Salary :</td>
                    <td align="left" bgcolor="#ffffff">&nbsp;{{college.lowest_salary}}</td>
                </tr>
                <tr valign="top">
                    <td bgcolor="#F9F3D7">Salary mean :</td>
                    <td bgcolor="#ffffff">&nbsp;{{college.salary_mean}} </td>
                    <td bgcolor="#F9F3D7">Salary median :</td>
                    <td bgcolor="#ffffff">&nbsp;{{college.salary_median}}</td>
                </tr>
                <tr valign="top">
                    <td bgcolor="#F9F3D7">Salary mode :</td>
                    <td bgcolor="#ffffff">&nbsp;{{college.salary_mode}}</td>
                    <td align="left" bgcolor="#F9F3D7">Companies visited :</td>
                    <td align="left" bgcolor="#ffffff">&nbsp;{{college.companies_visited}}</td>
                </tr>
                <tr valign="top">
                    <td align="left" bgcolor="#F9F3D7"> Total offers :</td>
                    <td align="left" bgcolor="#ffffff">&nbsp;{{college.total_offers}}</td>
                    <td align="left" bgcolor="#F9F3D7">Placement percent :</td>
                    <td align="left" bgcolor="#ffffff">&nbsp;{{college.placement_percent}}</td>
                </tr>
      

	            <tr align="center">
	                <td bgcolor="#F9F3D7" colspan="4" class="pt8" align="center">
                    {% if placement_analysis_available %}
	                    This placement data is of <b>Year: {{college.placement_data_year}}</b>, taken from the college website.<br> The latest data available on the website as of mid 2022 was taken. 
                    {% else %}
                        Some or all of the placement data

                        {% if college.placement_data_year %}
                            of <b>Year: {{college.placement_data_year}}</b>
                        {% endif %}

                        is not available for this college.<br>Because either the data was not available on the website, or the college was not present in <sup>#</sup>Top 50.
                    {% endif %}
                    </td>
	            </tr>
            </table>
            <br />
    
        </div>
        <br><br>




        
    <!-- placement details  -->

{% if placement_details_available %}
    <h3 class="heading" id="heading">Placement details</h2>
    <link rel="stylesheet" href="{% static 'home\layout.css' %}">
    <script type="text/javascript" src="{% static 'home\layout.js' %}"></script>

        <div class="container">
	
            <div class="table">
                <div class="table-header">
                    <div class="header__item"><a id="Slno" class="not_sort_keys keep" href="#">Sl.NO</a></div>
                    <div class="header__item"><a id="Company" class="not_sort_keys" href="#">Company</a></div>
                    <div class="header__item"><a id="Salary" class="sort_keys" href="#">Salary<sub>(in LPA)</sub></a></div>
                    <div class="header__item"><a id="Offers" class="sort_keys" href="#">Offers</a></div>
                
                </div>
                <div class="table-content">
                    {% for row in placement_data %} 
                        <div class="table-row">
                            <div class="table-data" id="tableSlno">{{row.0}}</div>
                            <div class="table-data" id="tableCompany">{{row.1.0}}</div>
                            <div class="table-data" id="tableSalary">{{row.1.1}}</div>
                            <div class="table-data" id="tableOffers">{{row.1.2}}</div>
                        </div>
                    {% endfor %}
                </div>	
            </div>
        </div>
{% endif %}

</body>
</html>